# docker-compose.prod.yml
services:
  # The API Service
  web:
    image: ghcr.io/${IMAGE_NAME}:latest
    restart: always
    ports:
      - "80:8000" 
    volumes:
      - shared_data:/shared_data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_API_KEY=${PREFECT_API_KEY}
    # Migrates DB, starts app
    command: >
      sh -c "alembic upgrade head && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000" 

  # The Worker Service, Scheduler
  worker:
    image: ghcr.io/${IMAGE_NAME}:latest
    restart: always
    volumes:
      - shared_data:/shared_data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_API_KEY=${PREFECT_API_KEY}
    command: python worker.py

volumes:
  shared_data:

